---
title: "STAT184_FinalProject"
format: html
editor: visual
---

## 
install.packages("dplyr")
install.packages("ggplot2")
library(readr)
datasets <- list(
cfb13 <- read_csv("COLLEGEFOOTBALLDATA/cfb13.csv"),
cfb14 <- read_csv("COLLEGEFOOTBALLDATA/cfb14.csv"),
cfb15 <- read_csv("COLLEGEFOOTBALLDATA/cfb15.csv"),
cfb16 <- read_csv("COLLEGEFOOTBALLDATA/cfb16.csv"),
cfb17 <- read_csv("COLLEGEFOOTBALLDATA/cfb17.csv"),
cfb18 <- read_csv("COLLEGEFOOTBALLDATA/cfb18.csv"),
cfb19 <- read_csv("COLLEGEFOOTBALLDATA/cfb19.csv"),
cfb20 <- read_csv("COLLEGEFOOTBALLDATA/cfb20.csv")
)
library(dplyr)
library(ggplot2)
ggplot(cfb13, aes(x = Off.Yards, y = Win)) + geom_point() + labs (title = "Offensive Yards vs Total Wins", x = "offensive yards", y = "total wins") + theme_classic() + scale_x_continuous(limits = c(2000, 9000)) + scale_y_continuous(limits = c(0,13)) 
ggplot(cfb20, aes(x = Off.Yards, y = Win)) + geom_point() + labs (title = "Offensive Yards vs Total Wins", x = "offensive yards", y = "total wins") + theme_classic() + scale_x_continuous(limits = c(2000, 9000)) + scale_y_continuous(limits = c(0,13)) 




